### ISSUE TITLE
Image fails to start in OSE 3.0.2 w/out privileged context

### ISSUE THREAD

**Issue by bretm** [jboss-dockerfiles/infinispan#10]
The following yaml yields a perpetually crashing pod in my environment unless I grant the pod a "privileged" security context:

```yaml
[root@192 ~]# cat unprivileged-infinispan-pod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: unprivileged-infinispan-server
  namespace: test4
spec:
  containers:
  - image: jboss/infinispan-server
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8181
      protocol: TCP
    - containerPort: 9990
      protocol: TCP
    - containerPort: 11211
      protocol: TCP
    - containerPort: 11222
      protocol: TCP
    imagePullPolicy: IfNotPresent
    name: infinispan-server
  restartPolicy: Always
```

When I add the following patch, the pod successfully starts:

```diff
[root@192 ~]# diff -u unprivileged-infinispan-pod.yaml privileged-infinispan-pod.yaml 
--- unprivileged-infinispan-pod.yaml	2015-11-11 12:07:29.417205199 -0500
+++ privileged-infinispan-pod.yaml	2015-11-09 11:12:03.113293337 -0500
@@ -1,11 +1,13 @@
 apiVersion: v1
 kind: Pod
 metadata:
-  name: unprivileged-infinispan-server
+  name: privileged-infinispan-server
   namespace: test4
 spec:
   containers:
   - image: jboss/infinispan-server
+    securityContext:
+      privileged: true
     ports:
     - containerPort: 8080
       protocol: TCP
[root@192 ~]# 
```

Attaching to the docker instance of the failed unprivileged pod shows no valid /opt/jboss/
